"""FCP 7 XML generation and parsing for the video pipeline.

Generates xmeml version="5" project files compatible with Final Cut Pro 7,
Premiere Pro, and Kdenlive import. Also parses FCP 7 XML exported from
those editors back into (start, end) time ranges.
"""

import xml.etree.ElementTree as ET
from xml.dom import minidom

from pipeline.edl import resolve_segments


def generate_fcp7_xml(
    edl_version: dict,
    source_video: str,
    sequence_name: str = "clip",
    fps: int = 30,
    width: int = 1920,
    height: int = 1080,
) -> str:
    """Generate FCP 7 XML (xmeml version="5") from an EDL version dict.

    Args:
        edl_version: EDL version dict with ``segments`` and ``trims`` keys.
        source_video: Absolute path (or URL) to the source media file.
        sequence_name: Name embedded in the <sequence> element.
        fps: Frames per second used for all frame math (default 30).
        width: Sequence width in pixels (default 1920).
        height: Sequence height in pixels (default 1080).

    Returns:
        XML string with declaration (<?xml version="1.0" encoding="utf-8"?>).
    """
    time_ranges = resolve_segments(
        edl_version["segments"], edl_version.get("trims", [])
    )

    # Total duration in frames
    total_frames = sum(int((end - start) * fps) for start, end in time_ranges)

    # --- Root ---
    xmeml = ET.Element("xmeml", version="5")

    # --- Sequence ---
    sequence = ET.SubElement(xmeml, "sequence")
    ET.SubElement(sequence, "name").text = sequence_name
    ET.SubElement(sequence, "duration").text = str(total_frames)

    rate = ET.SubElement(sequence, "rate")
    ET.SubElement(rate, "timebase").text = str(fps)
    ET.SubElement(rate, "ntsc").text = "FALSE"

    # --- Media ---
    media = ET.SubElement(sequence, "media")

    video_el = ET.SubElement(media, "video")
    video_track = ET.SubElement(video_el, "track")

    audio_el = ET.SubElement(media, "audio")
    audio_track = ET.SubElement(audio_el, "track")

    # --- Clip items ---
    timeline_cursor = 0  # running position on timeline in frames

    for i, (start, end) in enumerate(time_ranges):
        start_frame = int(start * fps)
        end_frame = int(end * fps)
        duration_frames = end_frame - start_frame

        tl_start = timeline_cursor
        tl_end = timeline_cursor + duration_frames

        for track in (video_track, audio_track):
            item = ET.SubElement(track, "clipitem", id=f"clipitem-{i + 1}")
            ET.SubElement(item, "in").text = str(start_frame)
            ET.SubElement(item, "out").text = str(end_frame)
            ET.SubElement(item, "start").text = str(tl_start)
            ET.SubElement(item, "end").text = str(tl_end)

            file_el = ET.SubElement(item, "file", id=f"file-{i + 1}")
            ET.SubElement(file_el, "pathurl").text = source_video

        timeline_cursor = tl_end

    # --- Serialise with declaration ---
    raw = ET.tostring(xmeml, encoding="unicode")
    pretty = minidom.parseString(raw).toprettyxml(
        indent="  ", encoding=None
    )
    # minidom.toprettyxml adds its own declaration; replace it with the
    # standard one (utf-8) and strip the blank first line it sometimes adds.
    lines = pretty.splitlines()
    # First line is the XML declaration from minidom; keep it but normalise.
    output_lines = ['<?xml version="1.0" encoding="utf-8"?>']
    for line in lines:
        stripped = line.rstrip()
        if stripped and not stripped.startswith("<?xml"):
            output_lines.append(stripped)

    return "\n".join(output_lines) + "\n"


def parse_fcp7_xml(xml_path: str) -> list[tuple[float, float]]:
    """Parse an FCP 7 XML file and return source time ranges.

    Reads the fps from ``<sequence><rate><timebase>`` and converts each
    ``<clipitem>``'s ``<in>``/``<out>`` frame numbers to seconds.

    Args:
        xml_path: Path to the .xml file exported from Premiere, Kdenlive, or
            generated by :func:`generate_fcp7_xml`.

    Returns:
        List of ``(start_seconds, end_seconds)`` tuples, one per clip item
        found in the first video track.
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    sequence = root.find("sequence")
    if sequence is None:
        raise ValueError(f"No <sequence> element found in {xml_path}")

    timebase_el = sequence.find("rate/timebase")
    if timebase_el is None or not timebase_el.text:
        raise ValueError(f"No <rate><timebase> found in {xml_path}")
    fps = int(timebase_el.text)

    results: list[tuple[float, float]] = []

    video_track = sequence.find("media/video/track")
    if video_track is None:
        return results

    for item in video_track.findall("clipitem"):
        in_el = item.find("in")
        out_el = item.find("out")
        if in_el is None or out_el is None:
            continue
        start_seconds = int(in_el.text) / fps
        end_seconds = int(out_el.text) / fps
        results.append((start_seconds, end_seconds))

    return results
